from __future__ import annotations

from typing import Any, Dict, List

from .orchestrator_contract import (
    DEFAULT_CONTEXT_POLICY,
    DEFAULT_MAX_CONCURRENT_SUBSESSIONS,
    DEFAULT_MAX_QUEUE_TURNS,
    DEFAULT_MAX_SUBSESSION_CALLS,
    DEFAULT_TERMINATION_POLICY,
    build_hermes_orchestrator_runtime_contract,
)
from .hermes_command_builder import _arg, _command


def default_commands_chunk_1() -> List[Dict[str, Any]]:
    return [
        _command(
            "/wsa_help",
            ["/wsa-help", "/wsa", "wsa help"],
            "Show the WSA shortcut menu.",
            "show_command_registry",
            "meta",
            "read_only",
            [],
            [["wsa", "hermes", "commands"]],
        ),
        _command(
            "/wsa_doctor",
            ["/wsa-doctor", "/wsa_diag", "/wsa-diagnose"],
            "Run local WSA and Hermes readiness diagnostics.",
            "run_diagnostics",
            "diagnostics",
            "read_only",
            [
                _arg(
                    "hermes_wrapper_command",
                    False,
                    "Hermes wrapper command visible inside the runtime.",
                    default="wsa-hermes-cli",
                ),
            ],
            [
                ["wsa", "doctor"],
                ["wsa", "manager", "diagnose"],
                ["wsa", "hermes", "doctor", "--command", "{hermes_wrapper_command}"],
            ],
        ),
        _command(
            "/wsa_worlds",
            ["/wsa-worlds", "/wsa_list_worlds"],
            "List registered worlds.",
            "list_worlds",
            "world",
            "read_only",
            [],
            [["wsa", "world", "list"]],
        ),
        _command(
            "/wsa_create_world",
            ["/wsa-create-world", "/wsa_new_world"],
            "Create a new isolated world workspace.",
            "create_world",
            "world",
            "requires_approval",
            [_arg("name", True, "Human-readable world name.")],
            [["wsa", "world", "create", "{name}"]],
        ),
        _command(
            "/wsa_startup",
            ["/wsa-startup", "/wsa_open_startup"],
            "Start or continue the open-ended startup interview.",
            "open_startup_interview",
            "startup",
            "workspace_mutating",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("budget", False, "Maximum startup questions for this round. Default: 4.", default=4),
            ],
            [
                ["wsa", "world", "startup", "status", "{world_id}", "--format", "json"],
                [
                    "wsa",
                    "world",
                    "startup",
                    "interview",
                    "{world_id}",
                    "--budget",
                    "{budget:4}",
                    "--format",
                    "json",
                ],
            ],
            [
                "This command may create or update startup_profile.json; do not run during update.lock.",
                "Use at most three choices per question and encourage longer free-text author answers.",
            ],
        ),
        _command(
            "/wsa_easystartup",
            ["/wsa-easystartup", "/wsa_easystart", "/wsa-easystart"],
            "Start or continue the easy-pick startup interview.",
            "easy_pick_startup_interview",
            "startup",
            "workspace_mutating",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("budget", False, "Maximum easy-pick questions for this round. Default: 8.", default=8),
            ],
            [
                ["wsa", "world", "easystartup", "status", "{world_id}", "--format", "json"],
                [
                    "wsa",
                    "world",
                    "easystartup",
                    "interview",
                    "{world_id}",
                    "--budget",
                    "{budget:8}",
                    "--format",
                    "json",
                ],
            ],
            [
                "This command may create or update startup_profile.json; do not run during update.lock.",
                "Offer five to eight easy-pick choices per question and let Hermes fill details according to discretion level.",
                "Hermes should keep returning to the interview with progress unless the user stops it.",
            ],
        ),
        _command(
            "/wsa_answer",
            ["/wsa-answer", "/wsa_startup_answer"],
            "Record an author answer for a startup question.",
            "record_startup_answer",
            "startup",
            "requires_approval",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("question_id", True, "Startup question ID such as 0001."),
                _arg("text", True, "Author-approved answer text."),
            ],
            [
                [
                    "wsa",
                    "world",
                    "startup",
                    "answer",
                    "{world_id}",
                    "{question_id}",
                    "--text",
                    "{text}",
                    "--format",
                    "json",
                ],
                [
                    "wsa",
                    "world",
                    "easystartup",
                    "answer",
                    "{world_id}",
                    "{question_id}",
                    "--text",
                    "{text}",
                    "--format",
                    "json",
                ],
            ],
            [
                "Hermes chooses the startup or easystartup answer endpoint based on the active interview mode.",
            ],
            template_execution="choose_one_by_active_mode",
        ),
        _command(
            "/wsa_pick",
            ["/wsa-pick", "/wsa_batch_answer", "/wsa-batch-answer"],
            "Record parallel startup choices such as 0001a 0002b plus notes.",
            "record_parallel_startup_choices",
            "startup",
            "requires_approval",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("text", True, "Answer text containing codes such as 0001a 0002b."),
            ],
            [
                [
                    "wsa",
                    "world",
                    "startup",
                    "batch-answer",
                    "{world_id}",
                    "--text",
                    "{text}",
                    "--format",
                    "json",
                ],
                [
                    "wsa",
                    "world",
                    "easystartup",
                    "batch-answer",
                    "{world_id}",
                    "--text",
                    "{text}",
                    "--format",
                    "json",
                ],
            ],
            [
                "Hermes chooses the startup or easystartup batch endpoint based on the active interview mode.",
            ],
            template_execution="choose_one_by_active_mode",
        ),
        _command(
            "/wsa_autogen",
            ["/wsa-autogen", "/wsa_random", "/wsa-random"],
            "Ask Hermes to generate world candidates until a natural-language checkpoint.",
            "autonomous_world_generation",
            "startup",
            "proposal_only",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg(
                    "checkpoint",
                    True,
                    "Natural-language stopping point, such as 'until the requested outline is ready for review'.",
                ),
                _arg("discretion", False, "Discretion level from 0 to 5. Default decided by Hermes/user dialogue."),
            ],
            [
                [
                    "wsa",
                    "hermes",
                    "task",
                    "{world_id}",
                    "--task-type",
                    "autonomous_world_generation",
                    "--title",
                    "Autonomous world generation",
                    "--instruction",
                    "{checkpoint}",
                    "--background",
                ]
            ],
            [
                "This command generates candidates only; canon mutation still follows user review policy.",
                "Discretion level 5 requires a destination checkpoint before cron automation starts.",
            ],
        ),
        _command(
            "/wsa_update",
            ["/wsa-update", "/wsa_upgrade", "/wsa-upgrade"],
            "Run update preflight before a Hermes-owned WSA source upgrade.",
            "preflight_wsa_update",
            "operations",
            "read_only",
            [
                _arg(
                    "source_root",
                    False,
                    "WSA source checkout or package root to inspect before update. Pass explicitly when known.",
                ),
            ],
            [
                [
                    "wsa",
                    "update",
                    "preflight",
                    "--source-root",
                    "{source_root}",
                    "--format",
                    "json",
                ]
            ],
            [
                "This command does not pull, overwrite, migrate, or delete files.",
                "If Hermes runs from the workspace root, pass the installed WSA source root explicitly or omit source_root.",
                "Hermes should run this before and after any runtime-owned source update.",
                "If preflight blocks, Hermes should stop update automation and report the blocking condition.",
            ],
        ),
        _command(
            "/wsa_update_backup",
            ["/wsa-update-backup", "/wsa_backup", "/wsa-backup"],
            "Create a workspace backup before a Hermes-owned WSA source upgrade.",
            "backup_before_wsa_update",
            "operations",
            "requires_approval",
            [
                _arg(
                    "output_dir",
                    True,
                    "Directory outside the workspace where the backup folder will be created.",
                ),
                _arg(
                    "source_root",
                    False,
                    "WSA source checkout or package root to inspect before backup. Pass explicitly when known.",
                ),
            ],
            [
                [
                    "wsa",
                    "update",
                    "backup",
                    "--output-dir",
                    "{output_dir}",
                    "--source-root",
                    "{source_root}",
                    "--format",
                    "json",
                ]
            ],
            [
                "This command creates a backup artifact only; it does not pull, overwrite, migrate, or delete source files.",
                "If Hermes runs from the workspace root, pass the installed WSA source root explicitly or omit source_root.",
                "Hermes should run update preflight before and after backup, then request approval for any source update command.",
            ],
        ),
        _command(
            "/wsa_orchestrator",
            ["/wsa-orchestrator", "/wsa_meetup", "/wsa-meetup"],
            "Run a manual-trigger autonomous orchestrator workflow.",
            "run_autonomous_orchestrator",
            "orchestrator",
            "proposal_only",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("workflow", False, "Workflow type such as meetup. Default: meetup.", default="meetup"),
                _arg(
                    "skill",
                    False,
                    "Hermes skill shortcut scope such as meetup or scene_start. Default: workflow.",
                    default="meetup",
                ),
                _arg("topic", True, "Topic or high-level request to orchestrate."),
                _arg("question", False, "Question to resolve during orchestration."),
                _arg("rounds", False, "Internal round budget. Default: 2.", default=2),
                _arg(
                    "max_queue_turns",
                    False,
                    "Maximum autonomous queue turns before stopping. Default: 12.",
                    default=DEFAULT_MAX_QUEUE_TURNS,
                ),
                _arg(
                    "max_concurrent_subsessions",
                    False,
                    "Maximum simultaneous subsessions before Hermes should batch work. Default: 4.",
                    default=DEFAULT_MAX_CONCURRENT_SUBSESSIONS,
                ),
                _arg(
                    "max_subsession_calls",
                    False,
                    "Maximum total subsession calls before partial report. Default: 48.",
                    default=DEFAULT_MAX_SUBSESSION_CALLS,
                ),
                _arg(
                    "context_policy",
                    False,
                    "Context carry-forward policy. Default: compressed-continuity.",
                    default=DEFAULT_CONTEXT_POLICY,
                ),
                _arg(
                    "frame_plan",
                    False,
                    "Optional user-defined plan/frame. Conservative default guardrail is used when omitted.",
                ),
                _arg(
                    "termination_policy",
                    False,
                    "Termination policy. Default: chair_or_conclusion_or_queue_limit.",
                    default=DEFAULT_TERMINATION_POLICY,
                ),
                _arg(
                    "participant",
                    False,
                    "Participant/viewpoint. May be repeated by Hermes.",
                    repeatable=True,
                ),
            ],
            [
                [
                    "wsa",
                    "orchestrator",
                    "run",
                    "{world_id}",
                    "--workflow",
                    "{workflow:meetup}",
                    "--skill",
                    "{skill:meetup}",
                    "--topic",
                    "{topic}",
                    "--question",
                    "{question:Synthesize proposals, conflicts, gaps, and approval options.}",
                    "--rounds",
                    "{rounds:2}",
                    "--max-queue-turns",
                    "{max_queue_turns:12}",
                    "--max-concurrent-subsessions",
                    "{max_concurrent_subsessions:4}",
                    "--max-subsession-calls",
                    "{max_subsession_calls:48}",
                    "--context-policy",
                    f"{{context_policy:{DEFAULT_CONTEXT_POLICY}}}",
                    "--frame-plan",
                    "{frame_plan}",
                    "--termination-policy",
                    f"{{termination_policy:{DEFAULT_TERMINATION_POLICY}}}",
                    "--participant",
                    "{participant}",
                    "--subsession-policy",
                    "ephemeral",
                    "--canon-policy",
                    "proposal-only",
                    "--approval",
                    "required",
                    "--close-on",
                    "complete",
                ]
            ],
            [
                "Manual trigger, then autonomous execution until review boundary or max queue turns.",
                "WSA declares the orchestration contract and audit artifact; Hermes owns actual subagent invocation.",
                "The template CLI produces local simulated subsession outputs unless a Hermes runtime uses the prompt packets to run real subagents.",
                "Hermes should preserve a compressed meeting context inside this run and adapt prompt packets to its subagent syntax.",
                "Hermes should not start without a plan/frame and hard limits; WSA supplies conservative defaults when the user has not customized them.",
                "Prep review is default-on in bridge mode; inspect prep_report and run wsa orchestrator prep-approve before actor/subagent calls unless the user opted out.",
                "Treat the run as a live meeting floor: participants receive compressed continuity until the chair closes it or a hard limit stops it.",
                "Subsession prompts should be short and precise; accumulate only outputs that pass the quality gate.",
                "Temporary subsessions are closed after the report package is created.",
                "Generated material stays proposal-only until explicit author approval.",
            ],
            runtime_contract=build_hermes_orchestrator_runtime_contract(),
        ),
        _command(
            "/wsa_scene_start",
            ["/wsa-scene-start", "/scene-start", "/wsa_scene_prep", "/wsa-scene-prep"],
            "Prepare a scene-generation lifecycle through the WSA orchestrator.",
            "run_scene_generation_orchestrator",
            "orchestrator",
            "proposal_only",
            [
                _arg("world_id", True, "World ID or active world selected by Hermes."),
                _arg("topic", True, "Scene or scene-prep topic."),
                _arg(
                    "question",
                    False,
                    "Scene-prep question to resolve before drafting.",
                    default=(
                        "Prepare scene facts, actor assignments, role isolation, "
                        "model/thinking guidance, and approval choices."
                    ),
                ),
                _arg("rounds", False, "Internal round budget. Default: 3.", default=3),
                _arg(
                    "max_queue_turns",
                    False,
                    "Maximum autonomous queue turns before stopping. Default: 12.",
                    default=DEFAULT_MAX_QUEUE_TURNS,
                ),
                _arg(
                    "max_concurrent_subsessions",
                    False,
                    "Maximum simultaneous actor/subsession calls before batching. Default: 4.",
                    default=DEFAULT_MAX_CONCURRENT_SUBSESSIONS,
                ),
                _arg(
                    "max_subsession_calls",
                    False,
                    "Maximum total actor/subsession calls before partial report. Default: 48.",
                    default=DEFAULT_MAX_SUBSESSION_CALLS,
                ),
                _arg(
                    "frame_plan",
                    False,
                    "Optional user-defined scene frame, viewpoint, location, timeframe, or guardrail.",
                ),
                _arg("time_scope", False, "Optional scene time scope."),
                _arg("location_scope", False, "Optional scene location scope."),
                _arg("viewpoint", False, "Optional viewpoint or POV scope."),
                _arg(
                    "generation_mode",
                    False,
                    "Scene mode: auto, fact-audit-synthesis, or writing-room-line-build. Default: auto.",
                    default="auto",
                ),
                _arg(
                    "condition",
                    False,
                    "Optional scene selection condition. May be repeated.",
                    repeatable=True,
                ),
                _arg(
                    "participant",
                    False,
                    "Actor, narrator, crowd, continuity role, or scene-prep viewpoint. May be repeated.",
                    repeatable=True,
                ),
                _arg(
                    "run_id",
                    False,
                    "Run ID returned by the start command; used when approving prep or fetching hook packets.",
                ),
            ],
            [
                [
                    "wsa",
                    "scene",
                    "start",
                    "{world_id}",
                    "--topic",
                    "{topic}",
                    "--question",
                    "{question:Prepare scene facts, actor assignments, role isolation, model/thinking guidance, and approval choices.}",
                    "--rounds",
                    "{rounds:3}",
                    "--max-queue-turns",
                    "{max_queue_turns:12}",
                    "--max-concurrent-subsessions",
                    "{max_concurrent_subsessions:4}",
                    "--max-subsession-calls",
                    "{max_subsession_calls:48}",
                    "--frame-plan",
                    "{frame_plan}",
                    "--time-scope",
                    "{time_scope}",
                    "--location-scope",
                    "{location_scope}",
                    "--viewpoint",
                    "{viewpoint}",
                    "--generation-mode",
                    "{generation_mode:auto}",
                    "--condition",
                    "{condition}",
                    "--participant",
                    "{participant}",
                    "--format",
                    "json",
                ],
                ["wsa", "orchestrator", "prep-approve", "{run_id}", "--format", "json"],
                ["wsa", "orchestrator", "next", "{run_id}", "--format", "json"],
            ],
            [
                "Manual trigger for scene-prep, not direct script canonization.",
                "The first template starts the run and returns a prep review report by default.",
                "The second template approves the prep report and opens the first Hermes actor hook for a returned run_id.",
                "The third template remains available when Hermes needs to fetch the next hook for a returned run_id.",
                "Scene prep should filter facts/history/memory by viewpoint, cross-check contradictions, assign actors, isolate multi-role sessions, recommend model/thinking levels, and stop at approval boundary.",
                "Hermes owns actual actor/subagent calls. WSA records prompt packets, floor state, turn records, quality gates, and approval package.",
            ],
            runtime_contract=build_hermes_orchestrator_runtime_contract(),
            input_json_template={
                "workflow": "scene_generation",
                "skill": "scene_start",
                "topic": "{topic}",
                "question": "{question:Prepare scene facts, actor assignments, role isolation, model/thinking guidance, and approval choices.}",
                "frame_plan": "{frame_plan}",
                "time_scope": "{time_scope}",
                "location_scope": "{location_scope}",
                "viewpoint": "{viewpoint}",
                "generation_mode": "{generation_mode:auto}",
                "condition": "{condition}",
                "participant": "{participant}",
                "boundary": "prep_package_before_scene_draft_or_canon_mutation",
            },
            template_execution="run_scene_start_then_review_prep_then_fetch_next_hook_by_run_id",
        ),
    ]
