"""Stable public facade for ticket proposal, review, and application workflows."""

from .application.ticket_revision_service import (
    MERGE_SIDE_EFFECT_STATUS,
    PREVIEW_SIDE_EFFECT_STATUS,
    SPLIT_SIDE_EFFECT_STATUS,
    TicketMergePreview,
    TicketMergeResult,
    TicketMergeSourcePreview,
    TicketMergeWriteResult,
    TicketRevisionService,
    TicketSplitGroupPreview,
    TicketSplitPreview,
    TicketSplitResult,
    TicketSplitWriteResult,
    merge_ticket_preview,
    merge_tickets,
    preview_merge_tickets,
    preview_split_ticket,
    preview_ticket_merge,
    preview_ticket_split,
    split_ticket,
    split_ticket_preview,
    write_ticket_merge,
    write_ticket_split,
)
from .ticket_application import apply_ticket, approve_ticket
from .ticket_contracts import (
    APPLIED_CONTENT_STATUSES,
    CANDIDATE_TICKET_TYPES,
    DEEP_AUTHORING_CHANGE_TYPES,
    DEEP_AUTHORING_TARGET_TYPES,
    FACT_STATUSES,
    KNOWLEDGE_STATES,
    KNOWLEDGE_TARGET_TABLES,
    PORTABLE_APPLY_ORDER,
    PORTABLE_CHANGE_TABLES,
    PROFILE_FRAGMENT_TYPES,
    PROPOSED_APPLY_COMPAT_WARNING,
    REVISIONABLE_TICKET_STATUSES,
    InvalidTicketStateError,
    NonApplicableTicketError,
    TicketApplyResult,
    UnsupportedTicketChangeError,
)
from .ticket_references import validate_deep_authoring_references
from .ticket_store import (
    create_pr_packet,
    create_revision_packet,
    materialize_candidate_ticket,
    review_ticket,
)
from .ticket_validation import validate_change_payloads

__all__ = [
    "APPLIED_CONTENT_STATUSES",
    "CANDIDATE_TICKET_TYPES",
    "DEEP_AUTHORING_CHANGE_TYPES",
    "DEEP_AUTHORING_TARGET_TYPES",
    "FACT_STATUSES",
    "KNOWLEDGE_STATES",
    "KNOWLEDGE_TARGET_TABLES",
    "MERGE_SIDE_EFFECT_STATUS",
    "PORTABLE_APPLY_ORDER",
    "PORTABLE_CHANGE_TABLES",
    "PREVIEW_SIDE_EFFECT_STATUS",
    "PROFILE_FRAGMENT_TYPES",
    "PROPOSED_APPLY_COMPAT_WARNING",
    "REVISIONABLE_TICKET_STATUSES",
    "SPLIT_SIDE_EFFECT_STATUS",
    "InvalidTicketStateError",
    "NonApplicableTicketError",
    "TicketApplyResult",
    "TicketMergePreview",
    "TicketMergeResult",
    "TicketMergeSourcePreview",
    "TicketMergeWriteResult",
    "TicketRevisionService",
    "TicketSplitGroupPreview",
    "TicketSplitPreview",
    "TicketSplitResult",
    "TicketSplitWriteResult",
    "UnsupportedTicketChangeError",
    "apply_ticket",
    "approve_ticket",
    "create_pr_packet",
    "create_revision_packet",
    "merge_ticket_preview",
    "merge_tickets",
    "materialize_candidate_ticket",
    "preview_merge_tickets",
    "preview_split_ticket",
    "preview_ticket_merge",
    "preview_ticket_split",
    "review_ticket",
    "split_ticket",
    "split_ticket_preview",
    "validate_change_payloads",
    "validate_deep_authoring_references",
    "write_ticket_merge",
    "write_ticket_split",
]
